server:
  context-path: /api/product
  port: 9008
  
security:
  oauth2:
    client:
      clientId: product
    
dongpinyun:
  openIdLoginPwdKey: ${OPENID_LOGIN_PWD_KEY:123456}
  maxValidateCodeSendPerIp: ${VALIDATE_CODE_SEND_IP_MAX:20}
  maxValidateCodeSendPerMobile: ${VALIDATE_CODE_SEND_MOBILE_MAX:20}

